### ISSUE TITLE
Dialog pre-selects a wrong  button

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenuLib#208]
**Describe the bug**
When creating a dialog, I set OK and Cancel button (in this exact order). I explicitly set the first button to be the active one, yet "Cancel" is pre-selected.

**Confirm that the bug is in the embedded library**
It is.

**To Reproduce**
Use the following code:
```cpp
withMenuDialogIfAvailable([](MenuBasedDialog* dlg) {
    dlg->setButtons(BTNTYPE_OK, BTNTYPE_CANCEL, 0);
    dlg->show(TC_I18N_SETTINGS_MEMORY_SAVE_SETTINGS_DLG_TITLE, true, [](ButtonType buttonPressed, void* yourData) {
        if (buttonPressed == BTNTYPE_OK) {
            storeManager.saveSettings();
        }
    });
    dlg->copyIntoBuffer(TC_I18N_SETTINGS_MEMORY_SAVE_SETTINGS_DLG_MESSAGE);
});
```

**Expected behavior**
OK button is pre-selected.

**Screenshots**
![image](https://github.com/davetcc/tcMenuLib/assets/4460766/cae647fd-23ac-4c35-a24d-a41c386ab416)

**Device Specs**
- ESP32 with custom display.

**Comment by davetcc** [comment]
This has been mainly fixed now, I think there is one case left to handle, and that is when a menu based dialog is shown when returning from a custom drawing routine. This seems to leave the wrong item selected.

Steps that reproduce:

1. Display has timed out to a dashboard instead of presenting a menu, IE the display has been taken over
2. A remote pairing request arrives that causes a dialog to be presented, therefore ending the display take over.
3. When the dialog appears, no item we be active.

**Comment by davetcc** [comment]
@vzahradnik  closing this as I've tested it fairly thoroughly now, but if you find any issue still remaining please raise.
